// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6IGi1PgG4vUtMFlVgEMEYe1EoqMqTvJk',
    appId: '1:775315883248:android:4549991665a0401e28ee35',
    messagingSenderId: '775315883248',
    projectId: 'fue-connect-f5213',
    databaseURL: 'https://fue-connect-f5213-default-rtdb.firebaseio.com',
    storageBucket: 'fue-connect-f5213.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAppFi-iwdZz5y5r4D-DcRoQhccPTgwDCs',
    appId: '1:775315883248:ios:60db89a3ef2d8a4128ee35',
    messagingSenderId: '775315883248',
    projectId: 'fue-connect-f5213',
    databaseURL: 'https://fue-connect-f5213-default-rtdb.firebaseio.com',
    storageBucket: 'fue-connect-f5213.firebasestorage.app',
    iosClientId: '775315883248-cs791js2bkr0fa1030fhpbrg2o8faojh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fueConnect',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbR7dDvQHKXW7VyAdo-0tZoeeVwIFXZdk',
    appId: '1:775315883248:web:a50b59026864f0d628ee35',
    messagingSenderId: '775315883248',
    projectId: 'fue-connect-f5213',
    authDomain: 'fue-connect-f5213.firebaseapp.com',
    databaseURL: 'https://fue-connect-f5213-default-rtdb.firebaseio.com',
    storageBucket: 'fue-connect-f5213.firebasestorage.app',
    measurementId: 'G-XSRPJB84Z7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAppFi-iwdZz5y5r4D-DcRoQhccPTgwDCs',
    appId: '1:775315883248:ios:60db89a3ef2d8a4128ee35',
    messagingSenderId: '775315883248',
    projectId: 'fue-connect-f5213',
    databaseURL: 'https://fue-connect-f5213-default-rtdb.firebaseio.com',
    storageBucket: 'fue-connect-f5213.firebasestorage.app',
    iosClientId: '775315883248-cs791js2bkr0fa1030fhpbrg2o8faojh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fueConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbR7dDvQHKXW7VyAdo-0tZoeeVwIFXZdk',
    appId: '1:775315883248:web:2024b9e7c326ed1028ee35',
    messagingSenderId: '775315883248',
    projectId: 'fue-connect-f5213',
    authDomain: 'fue-connect-f5213.firebaseapp.com',
    databaseURL: 'https://fue-connect-f5213-default-rtdb.firebaseio.com',
    storageBucket: 'fue-connect-f5213.firebasestorage.app',
    measurementId: 'G-XJL04BV1Y4',
  );

}